### PR TITLE
logo design

### PR DESCRIPTION
**Pull request by dulnan**
Here's a possible logo for Buttercoin. There are two different font options: logo1.png is a bit "fancy" while logo2.png is more "classic".

### CODE REVIEW

**Comment by PartTimeLegend** [comment]
Please provide source files also.

**Comment by Marak** [comment]
The melting bitcoin is probably not the best messaging. It might be nice to have a normal bitcoin next to a pad of butter sitting on a serving tray. Maybe a bit more classy.

**Comment by JulianNorton** [comment]
Both of these seem off, I don't think the melting (meltdown anyone?) is the right approach. Also, keep in mind that there will have to be a favicon version.

_edit_

I really like the font choice for the first one, it's different from the rest of the companies out there, and the emphasis that we _are_ different, in a good way.

**Comment by dulnan** [comment]
@JulianNorton That actually makes sense (meltdown). Didn't even cross my mind. Okay, let's see what I can do.

@PartTimeLegend I'll provide a SVG as soon as there is a final idea for the logo.

**Comment by PartTimeLegend** [comment]
Closing as logo is not meeting general consensus. Please submit a new pull with future logo designs.

**Pull request closed without merging**
