### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PartTimeLegend**
A bit of a nicer README. It's a first draft, but we need some kind of nice introduction.

### CODE REVIEW

**Comment by patcon** [comment]
What do you think about adding a "Usage" section, complete with instructions on installing Node and running npm, etc.

I know it's mostly technical people, but who know who might want to evaluate it. Let's just bring the barrier to entry as low as possible for anyone to participate :)

**Comment by PartTimeLegend** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

I think there would be a better use for a docs directory for additional things like install.

I can't see many people struggling with aptitude install nodejs. Then again I could create a bash script to install and configure the whole package.

I'm at a boxing match at the moment, so I'll do this tomorrow if there is much call.

Patrick Connolly notifications@github.com wrote:

> What do you think about adding a "Usage" section, complete with
> instructions on installing Node and running npm, etc.
> 
> I know it's mostly technical people, but who know who might want to
> evaluate it. Let's just bring the barrier to entry as low as possible
> for anyone to participate :)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/buttercoin/buttercoin/pull/8#issuecomment-16339823

---

Sent from my Android phone with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.0.8

iQFGBAEBCAAwBQJRab1UKRxBbnRvbnkgQmFpbGV5IDxzdXBwb3J0QGFudG9ueWJh
aWxleS5uZXQ+AAoJENGNqDzy5QAnBkwH/Rfv69pDjO4X52/DC7A9zIOxaNNhz/EE
jOMmnQzEVk20RGjj+6G07MkwnQmuosDvgabJffcW9RnwI1irLK2B/RgT5V+AEVsh
pFmeE+QbQo4vhEJCbVGshxhkNLtMFng3W/4Okl/ivJ+oDEecDAXvtDk3cdj6LSZ3
HdOAMPVd4uWTJ68IqggazmRy7B0dXx19N5syF8LYeOa2x7I9QFH1U97sWMfo+JUx
ExMbh6D05IZkxwGGxBoxtzk0T4GEfDRmf66M0WE2A09fe2NqPgyFpO1C137m3T5s
r+7XJmymBrWGFehGZNlO+IggYBRBH1s9nDA2yF+EFAtD0ezQlE9cHQw=
=IJq4
-----END PGP SIGNATURE-----

**Comment by patcon** [comment]
haha a boxing match? Amazing.

I'm sure you're mostly right. Just thinking it couldn't hurt.

One more thing: Think we could add a link to the original Reddit post for verification?
Re: http://www.reddit.com/r/Bitcoin/comments/1ca635/lets_discuss_expectations_for_open_source_bitcoin/

**Comment by PartTimeLegend** [comment]
Updated as per Patcon's request.

**Pull request merged**
