### PR TITLE
Added a simple order matching engine in cpp

### PR DESCRIPTION
**Pull request by rickardnorlander**
Can handle 1,000,000 order adds and matches in 1.4 seconds on my laptop. Very basic so far.

### CODE REVIEW

**Comment by enki** [comment]
nice. i can't really look at this in detail just now, but thanks!

**Comment by PartTimeLegend** [comment]
As the code needs fixing and you have mentioned that you have moved to a new repo. Do you wish to continue this pull?

**Comment by RevCBH** [comment]
It should probably stay in a separate repo unless it's integrated w/ bindings, etc.

**Comment by PartTimeLegend** [comment]
I'm going to close this until it's in a state of use.

**Pull request closed without merging**
