### PR TITLE
Big decimal

### PR DESCRIPTION
**Pull request by pghalliday**
Adding BigDecimal support but forcing amounts to be strings at the edge (DataStore.add_deposit)

### CODE REVIEW

**Comment by PartTimeLegend** [comment]
Let me get this straight. You want to deal with number values as strings and then convert back to numerical?

The extra calls to instantiate new BigDecimal() must carry an overhead also. I may be missing something, but I can't see the benefit of this. I can only see a slow down.

If we are calculating values in Satoshi's then a uint should be sufficient.

If I'm missing something, please tell me.

**Comment by pghalliday** [comment]
Well there was some discussion about using ints and multipliers but then the discussion went a bit awry when talking about how big the multiplier should be. Satoshis may be good for BTC but may not make much sense for USD. For now I think we figured it would be best to use a format that would not result in rounding errors.

Javascript Numbers are definitely not a good idea because `0.1 + 0.2 !== 0.3`

Also using Numbers to construct BigDecimals doesn't work for (possibly) the same reason. Ie.

`(new BigDecimal(0.1)).add(new BigDecimal(0.2)).compareTo(new BigDecimal(0.3)) !== 0`

However using strings and BigDecimal seems to avoid errors, ie. 

`(new BigDecimal('0.1')).add(new BigDecimal('0.2')).compareTo(new BigDecimal('0.3')) === 0`

I realised this may be controversial hence the branch

**Comment by PartTimeLegend** [comment]
JS takes the type of the left assignment.

`1 + "2" = 3`
`"1" + 2 = "12"`

I guess the thing that's throwing me is the whole decimal to string to decimal. I just see this as poor practice and I can't quite get my head around it. I think we need more devs in here to discuss this.

I'm happy to go with general consensus, however I have my reservations.

I'm trying to avoid too many branches as we could end up developing independent systems that can't be easily merged.

**Comment by pghalliday** [comment]
This isn't about type coercion it's about the Javascript Number type being inherently inaccurate. I should have been more explicit in my example. In javascript:

`0.1 + 0.2 === 0.30000000000000004`

Try it at a node prompt. It's just plain weird ;)

In practice I think numbers may even start out as strings as that's how users will enter them (in fact we don't ever want to express them as Numbers if we can avoid it)

Agreed on the branch thing, would be good to get this merged or rejected asap

**Comment by RevCBH** [comment]
Numeric values in Javascript are floating point by default and are therefore inherently inaccurate to some degree (see:  [here](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) for a lengthy discussion). You have to do silly tricks like bitwise or with zero to force integer values in JS. Since we're not only focused on BTC, it makes sense to support arbitrary precision which rules out fixed size integers anyway.

Adopting BigDecimal as an internal representation makes sense, assuming that it doesn't meaningfully affect performance in a negative fashion. The same goes for serializing to/from a string representation. If there are negative performance implications we can always create a custom solution down the road.

I think this change is good.

**Comment by enki** [comment]
yeah it's a good change. it will hurt performance, but it's good for the
"executable spec" goal. it's the more robust choice over
tiny_base+multiplier. if we run into performance problems we'll start
optimizing, but i think v1 will be more than fast enough with the promise
of v2 and v3 being way faster. i think the core exchange will actually
quite small, so let's just get it working correctly.

**Comment by vikstrous** [comment]
Have you guys considered using C++ bindings to make your own number objects? Maybe that's a terrible idea, maybe it's already been done. I haven't checked. Just a thought.

**Comment by enki** [comment]
not a bad idea, but premature optimization. let's get this thing running at
all first. loosely coupled, then improve.

**Comment by dhobbs** [comment]
Done very similar things before (in Java which punishes you for it with strong typing). I'd recommend an Amount type and encapsulate the representation inside it. It's quicker to start with the abstraction than to go through and fix everything later.

Strings are the 'safest' representation - no magic. I believe when using bigdecimal you need to be careful with the precision and rounding modes.

**Comment by pghalliday** [comment]
Having an Amount type sounds like the way to go - it can be a BigDecimal internally for now and I can force the constructor to only accept strings.

This will give us greatest flexibility I think when we have to deal with the legal rounding rules that seem to be inevitable.

**Comment by pghalliday** [comment]
I'm withdrawing this pull request and will delete the branch in favour of starting again with a new Amount class (if it's not already done)

**Comment by jperl** [comment]
@pghalliday [This](https://github.com/MikeMcl/big.js/) is also worth checking out

**Comment by pghalliday** [comment]
looks very interesting, thanks :)

**Comment by RevCBH** [comment]
@pghalliday I've been working on this for the last few hours and am realizing that integers with multipliers are likely the way to go. Even with things like BigDecimal, BigRational, etc. I haven't been able to get consistent precision when dividing numbers (for price calculation). Big.js might be worth a try, but if it doesn't work out I think integer is the way to go.

**Comment by pghalliday** [comment]
@RevCBH I know what you mean, although I went a different way and avoided divisions altogether where I could. I found they're only necessary if you allow pricing either way and thus have to match bids with bids or offers with offers. Even then though, I only had to do a division at the last moment to calculate the trade amounts for debiting and crediting, so the rounding errors don't build up and at least the books always balance.

This is in https://github.com/pghalliday/currency-market/blob/master/src/Order.coffee in the match method if you want to see how I avoid calculating prices.

Having said that when i swapped in Big.js I found the integer math was blazing fast (compared to BigDecimal) but the non integer math was noticeably slower. I had a simple test that just moved an integer amount through lots of accounts that went from 1,800 trades/sec on my laptop  to 10,000 but then a more realistic(?) random Bid/Offer test dropped from 1,200 to 1,000. However a random Offer/Offer test went up from around 300 to 500, so maybe Big.js is better at those divisions.

I did do some experiments early on with recording divisors in the amount type rather than actually doing divisions. But they soon multiply up to ridiculous numbers and kill performance (at least with BigDecimal). However there may be some mileage in using Big.js to just do integer math and implementing our own rounding and scaling for the divisions (at least that's this minute's thought)

**Pull request closed without merging**
